# Generated by Django 5.0.2 on 2024-02-29 16:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='课程编号')),
                ('courseName', models.CharField(max_length=100, unique=True, verbose_name='课程名称')),
                ('credit', models.IntegerField(verbose_name='学分')),
                ('classifier', models.CharField(max_length=1, verbose_name='课程类别')),
                ('attribute', models.SmallIntegerField(verbose_name='课程属性')),
                ('semester', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='请填入第几学期', regex='第\\s*(\\d+)\\s*学期')], verbose_name='课程所属学期')),
            ],
            options={
                'verbose_name': '课程库',
                'verbose_name_plural': '课程库',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='学院编号')),
                ('departmentName', models.CharField(max_length=100, unique=True, verbose_name='学院名称')),
            ],
            options={
                'verbose_name': '学院信息表',
                'verbose_name_plural': '学院信息表',
            },
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_group', to='app01.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '班级课程信息表',
                'verbose_name_plural': '班级课程信息表',
            },
        ),
        migrations.CreateModel(
            name='CourseTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_teacher', to='app01.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程教师信息表',
                'verbose_name_plural': '课程教师信息表',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupName', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='班级')),
                ('grade', models.SmallIntegerField(verbose_name='班级所属年级')),
                ('course', models.ManyToManyField(related_name='group_set', through='app01.CourseGroup', to='app01.course', verbose_name='所开课程')),
            ],
            options={
                'verbose_name': '班级库',
                'verbose_name_plural': '班级库',
            },
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_group', to='app01.group', verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='course',
            name='groups',
            field=models.ManyToManyField(related_name='courses_set', through='app01.CourseGroup', to='app01.group', verbose_name='开课班级'),
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='专业代号')),
                ('majorName', models.CharField(max_length=100, unique=True, verbose_name='专业名称')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department', to_field='departmentName', verbose_name='专业所属学院')),
            ],
            options={
                'verbose_name': '专业库',
                'verbose_name_plural': '专业库',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.major', to_field='majorName', verbose_name='班级所在专业'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='学生姓名')),
                ('idNumber', models.CharField(max_length=18, unique=True, verbose_name='身份证号码')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('ethnicity', models.CharField(default='汉族', max_length=10, verbose_name='民族')),
                ('enterYear', models.DateField(verbose_name='入学年份')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department', to_field='departmentName', verbose_name='所在学院')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.group', verbose_name='所在班级')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.major', to_field='majorName', verbose_name='所在专业')),
            ],
            options={
                'verbose_name': '学生库',
                'verbose_name_plural': '学生库',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='教师工号')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='教师姓名')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('course', models.ManyToManyField(related_name='teachers_set', through='app01.CourseTeacher', to='app01.course', verbose_name='所授课程')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department', to_field='departmentName', verbose_name='学院（部门）')),
            ],
            options={
                'verbose_name': '教师库',
                'verbose_name_plural': '教师库',
            },
        ),
        migrations.AddField(
            model_name='courseteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_teacher', to='app01.teacher', verbose_name='教师'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(related_name='courses_set', through='app01.CourseTeacher', to='app01.teacher', verbose_name='科任教师'),
        ),
    ]
