# Generated by Django 5.0.2 on 2024-03-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='attribute',
            field=models.SmallIntegerField(choices=[(1, '通识性课程'), (1, '公共选修课'), (3, '专业基础课'), (4, '专业必修课'), (5, '专业选修课'), (6, '素质拓展课'), (7, '独立实践环节')], verbose_name='课程属性'),
        ),
    ]
