# Generated by Django 5.0.2 on 2024-03-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_course_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='classifier',
            field=models.CharField(choices=[('A', '纯理论课'), ('B', '理论+实践'), ('C', '纯实践课')], max_length=1, verbose_name='课程类别'),
        ),
    ]
