# Generated by Django 5.0.2 on 2024-03-01 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_course_classifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_group', to='app01.group', verbose_name='班级'),
        ),
    ]
