# Generated by Django 5.0.2 on 2024-03-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_coursegroup_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.ImageField(default='static/img_course/default.jpg', upload_to='static/img_course', verbose_name='课程封面'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='img',
            field=models.ImageField(default='static/img_teacher/default.jpg', upload_to='static/img_teacher', verbose_name='教师照片'),
        ),
    ]
