# Generated by Django 5.0.2 on 2024-03-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_course_img_alter_teacher_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(default='', upload_to='', verbose_name='课程封面'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='img',
            field=models.ImageField(default='', upload_to='', verbose_name='教师照片'),
        ),
    ]
