# Generated by Django 5.0.2 on 2024-03-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_course_img_alter_teacher_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='groups',
            field=models.ManyToManyField(default='', related_name='courses_set', through='app01.CourseGroup', to='app01.group', verbose_name='开课班级'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(default='', related_name='courses_set', through='app01.CourseTeacher', to='app01.teacher', verbose_name='科任教师'),
        ),
    ]
