# Generated by Django 5.0.2 on 2024-03-02 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_alter_course_groups_alter_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
    ]
